export const greekCities = [
  "Athens",
  "Thessaloniki",
  "Patras",
  "Piraeus",
  "Heraklion",
  "Larissa",
  "Peristeri",
  "Acharnes",
  "Kallithea",
  "Kalamaria",
  "Glyfada",
  "Nikaia",
  "Volos",
  "Ilion",
  "Evosmos",
  "Chalandri",
  "Ilioupoli",
  "Keratsini",
  "Nea Smyrni",
  "Marousi",
  "Agios Dimitrios",
  "Zografou",
  "Egaleo",
  "Ioannina",
  "Palaio Faliro",
  "Nea Ionia",
  "Chalcis",
  "Agia Paraskevi",
  "Trikala",
  "Korydallos",
  "Petroupoli",
  "Alexandroupoli",
  "Serres",
  "Katerini",
  "Vyronas",
  "Kalamata",
  "Xanthi",
  "Galatsi",
  "Rhodes",
  "Chania",
  "Komotini",
  "Kavala",
  "Agrinio",
  "Irakleio",
  "Kifissia",
  "Lamia",
  "Chaidari",
  "Stavroupoli",
  "Drama",
  "Kozani",
  "Veria",
  "Alimos",
  "Karditsa",
  "Polichni",
  "Pylaia",
  "Ampelokipoi",
  "Rethymno",
  "Sykies",
  "Ano Liosia",
  "Gerakas",
  "Mytilene",
  "Argyroupoli",
  "Vrilissia",
  "Agioi Anargyroi",
  "Nea Ionia",
  "Ptolemaida",
  "Voula",
  "Aspropyrgos",
  "Cholargos",
  "Koropi",
  "Corinth",
  "Corfu",
  "Giannitsa",
  "Tripoli",
  "Metamorfosi",
  "Kamatero",
  "Megara",
  "Chios",
  "Agia Varvara",
  "Kaisariani",
  "Eleftherio-Kordelio",
  "Pyrgos",
  "Neapoli",
  "Perama",
  "Moschato",
  "Nea Filadelfeia",
  "Salamina",
  "Eleusis",
  "Kilkis",
  "Arta",
  "Oraiokastro",
  "Melissia",
  "Pallini",
  "Dafni",
  "Livadeia",
  "Artemida",
  "Argos",
  "Thebes",
  "Kos",
  "Pefki",
  "Preveza",
  "Aigio",
  "Orestiada",
  "Thermi",
  "Nea Erythraia",
  "Amaliada",
  "Nea Makri",
  "Naousa",
  "Edessa",
  "Sparta",
  "Kalymnos",
  "Ierapetra",
  "Panorama",
  "Florina",
  "Peraia",
  "Vari",
  "Elliniko",
  "Kastoria",
  "Gazi",
  "Paiania",
  "Alexandreia",
  "Kalyvia Thorikou",
  "Efkarpia",
  "Agios Ioannis Renti",
  "Rafina",
  "Nafplio",
  "Tavros",
  "Menemeni",
  "Missolonghi",
  "Papagou",
  "Loutraki",
  "Drapetsona",
  "Agios Nikolaos",
  "Pefka",
  "Nea Alikarnassos",
  "Spata",
  "Nafpaktos",
  "Ialysos",
  "Grevena",
  "Mandra",
  "Glyka Nera",
  "Diavata",
  "Tyrnavos",
  "Sitia",
  "Ermoupoli",
  "Argostoli",
  "Neo Psychiko",
  "Agios Stefanos",
  "Ymittos",
  "Anatoli",
  "Igoumenitsa",
  "Nea Artaki",
  "Nea Moudania",
];
